#!/bin/bash

SRC=linio.ts
DATA=../data
OUT=a.out

export DIST=dist
export PUBLIC=public

serve() {
  p:set_import public
  bun run --define DEV=true --hot $SRC $DATA
}

build() {
  p:set_import dist
  bun run build.ts
  bun build --define DEV=false --compile $SRC --outfile $OUT
  p:set_import public
}

install() {
  cp $OUT ${XDG_BINARY_HOME:-$HOME/.local/bin}/linio
}

clean() {
  rm -rf dist/*
  rm -rf $OUT
}

p:set_import() {
  case "$1" in
    public)
      sed -E 's|\./dist/|\./public/|' linio.ts > linio.ts.tmp && mv -f linio.ts.tmp linio.ts
      ;;
    dist)
      sed -E 's|\./public/|\./dist/|' linio.ts > linio.ts.tmp && mv -f linio.ts.tmp linio.ts
      ;;
  esac
}