<?php
// Adapter for PostgreSQL databases.

namespace adapter;
use PDO;

function establish_connection() {
  global $_DATABASE;

  $host = $_DATABASE['host'];
  $user = $_DATABASE['user'];
  $pass = $_DATABASE['pass'];
  $port = $_DATABASE['port'] ?? 5432;
  $name = ltrim($_DATABASE['path'], "/");

  $options = [
    PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    PDO::ATTR_EMULATE_PREPARES   => false,
  ];

  $dsn = "pgsql:host=$host;port=$port;dbname=$name";
  $dbh = new PDO($dsn, $user, $pass, $options);

  register_functions($dbh);

  return $dbh;
}

function register_functions($dbh) {
  $dbh->exec("CREATE EXTENSION IF NOT EXISTS unaccent");

  if(!function_defined($dbh, 'EXO_NORMALIZE')) $dbh->exec('CREATE FUNCTION EXO_NORMALIZE(input text)
    RETURNS text
    LANGUAGE SQL
    STABLE STRICT PARALLEL SAFE
    AS $$ SELECT unaccent(lower(input)) $$');
}

function expand_macros($sql) {
  return preg_replace(
    "/EXO_CONCAT\(\s*([^,]+?)\s*,\s*('(?:[^']|'')*')\s*\)/i",
    'STRING_AGG(($1)::text, $2)',
    $sql
  );
}

function function_defined($dbh, $name) {
  $query = $dbh->prepare('SELECT 1
    FROM pg_proc
    JOIN pg_namespace ON pg_namespace.oid = pg_proc.pronamespace
    WHERE pg_namespace.nspname = current_schema()
      AND pg_proc.proname = LOWER(?)');
  $query->execute([$name]);
  return !!$query->fetch();
}

function initial_run() {
  return !table_exists('migrations');
}

function execute($path) {
  $queries = explode(';', file_get_contents($path));

  foreach ($queries as $query) {
    $query = trim($query);
    if(empty($query)) continue;

    $query = str_replace(
      ["int(11) NOT NULL AUTO_INCREMENT", "datetime", "mediumblob"],
      ["integer GENERATED BY DEFAULT AS IDENTITY", "timestamp", "bytea"],
      $query
    );

    $query = preg_replace('/int\(\d+\)/', "integer", $query);

    DBH->exec($query);
  }
}

function table_exists($table_name) {
  $stmt = DBH->prepare("SELECT table_name
    FROM information_schema.tables
    WHERE table_catalog = current_database()
      AND table_schema = 'public'
      AND table_name = ?");

  $stmt->execute([$table_name]);
  return $stmt->fetch() != false;
}